# Generated by Django 3.2.13 on 2022-08-31 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herbarium.family')),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sun_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herbarium.genus')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_name', models.CharField(max_length=30)),
                ('last_watered', models.DateTimeField()),
                ('soil_preference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herbarium.soil')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herbarium.species')),
                ('sun_preference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herbarium.sun_preference')),
            ],
        ),
    ]
