# Generated by Django 3.2.16 on 2022-11-25 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Herbarium.family')),
            ],
            options={
                'verbose_name': 'Genus',
                'verbose_name_plural': 'Genera',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_name', models.CharField(blank=True, max_length=30, null=True)),
                ('complementary_name', models.CharField(blank=True, max_length=30, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_watered', models.DateField(null=True)),
                ('last_fertilized', models.DateField(null=True)),
                ('is_dead', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ['popular_name'],
            },
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Soil',
                'verbose_name_plural': 'Soils',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sun_regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sun preference',
                'verbose_name_plural': 'Sun preferences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Herbarium.genus')),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_images', verbose_name='Picture of a plant')),
                ('is_banner', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Herbarium.plant', verbose_name='Plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='soil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Herbarium.soil'),
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Herbarium.species'),
        ),
        migrations.AddField(
            model_name='plant',
            name='sun_regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Herbarium.sun_regime'),
        ),
        migrations.AddField(
            model_name='family',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Herbarium.group'),
        ),
    ]
