# Generated by Django 4.1 on 2022-09-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(null=True),
        ),
    ]
