# Generated by Django 3.2.16 on 2022-11-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Herbarium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_fertilized',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(null=True),
        ),
    ]
