# Generated by Django 4.1 on 2022-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0002_alter_plant_last_watered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'ordering': ['name'], 'verbose_name': 'Genus', 'verbose_name_plural': 'Genera'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['popular_name'], 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterModelOptions(
            name='soil',
            options={'ordering': ['name'], 'verbose_name': 'Soil', 'verbose_name_plural': 'Soils'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='sun_preference',
            options={'ordering': ['name'], 'verbose_name': 'Sun preference', 'verbose_name_plural': 'Sun preferences'},
        ),
        migrations.AddField(
            model_name='soil',
            name='description',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
