# Generated by Django 4.1 on 2022-09-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0005_alter_species_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='complementary_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='custom_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='popular_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
