# Generated by Django 4.1 on 2022-09-10 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herbarium', '0006_plant_complementary_name_plant_custom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
