# Generated by Django 4.1 on 2022-09-16 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0007_plant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_images', verbose_name='Picture of a plant')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbarium.plant', verbose_name='Plant')),
            ],
        ),
    ]
