# Generated by Django 4.1 on 2022-09-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0008_plantimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimages',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
