# Generated by Django 4.1 on 2022-09-21 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0009_plantimages_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimages',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='herbarium.plant', verbose_name='Plant'),
        ),
    ]
