# Generated by Django 4.1 on 2022-10-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0010_alter_plantimages_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='complementary_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='custom_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='popular_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
