# Generated by Django 4.1 on 2022-10-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0012_plant_last_fertilized_alter_family_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='soil_preference',
            new_name='soil',
        ),
    ]
