# Generated by Django 4.1 on 2022-10-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0013_rename_soil_preference_plant_soil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantImages',
            new_name='PlantImage',
        ),
    ]
